spring:
  profiles:
    active: dev
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: authentication-service
          uri: ${AUTHENTICATION_SERVICE_URL:lb://AUTHENTICATION-SERVICE}
          predicates:
            - Path=/authentication/**
        - id: company-service
          uri: ${COMPANY_SERVICE_URL:lb://COMPANY-SERVICE}
          predicates:
            - Path=/company/**
        - id: customer-service
          uri: ${CUSTOMER_SERVICE_URL:lb://CUSTOMER-SERVICE}
          predicates:
            - Path=/customer/**
        - id: finance-service
          uri: ${FINANCE_SERVICE_URL:lb://FINANCE-SERVICE}
          predicates:
            - Path=/finance/**
        - id: eureka-server
          uri: ${SERVICE_REGISTRY_URL:http://service-registry:8761/}
          predicates:
            - Path=/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: ${SERVICE_REGISTRY_URL:http://localhost:4200/}

logging:
  level:
    root: info
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinitionLocator: INFO

#Eureka
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
