spring:
  application:
    name: gateway-service
  cloud:
    kubernetes:
      discovery:
        enabled: true
    gateway:
      routes:
        - id: authentication-service
          uri: http://authentication-service
          predicates:
            - Path=/authentication/**
        - id: company-service
          uri: http://company-service
          predicates:
            - Path=/company/**
        - id: customer-service
          uri: http://customer-service
          predicates:
            - Path=/customer/**
logging:
  level:
    root: info
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinitionLocator: INFO

#Eureka
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    enabled: false