spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8180/
  cloud:
    config:
      discovery:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
